---
abstract: 'convert pictogram entities'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Base: 0.6
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Entities-ConvertPictogramMobileJp
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Encode::JP::Mobile: 0.25
  HTTP::MobileAgent: 0.26
  Params::Validate: 0.89
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
